import assert from 'node:assert/strict';
import {readFileSync,writeFileSync,mkdirSync,mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {JSDOM} from 'jsdom';
import {buildComponents} from '../tools/build-components.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
const load=paths=>{const dom=new JSDOM('<div id="root"></div>',{runScripts:'outside-only'});for(const p of [paths.runtime,paths.components])dom.window.eval(readFileSync(p,'utf8'));return dom;};
const actual=await buildComponents({root,outDir:join(root,'.tmp/runtime')});
const dom=load(actual);const api=dom.window.AuroraWebDesignSystem_96e210;
assert.equal(typeof api.DsButton,'function');assert.equal(typeof api.DsStringsProvider,'function');assert.equal(api.__errors,undefined);
const baseline=new JSDOM('',{runScripts:'outside-only'});
for(const f of ['components/lib/react.production.min.js','components/lib/react-dom.production.min.js','components/bundle.js'])baseline.window.eval(readFileSync(join(root,'.tmp/migration/original',f),'utf8'));
for(const name of Object.keys(baseline.window.AuroraWebDesignSystem_96e210).filter(n=>!n.startsWith('__')))assert.ok(name in api,`preserved export: ${name}`);
dom.window.close();baseline.window.close();
const fixture=mkdtempSync(join(tmpdir(),'aurora components пробел '));
try {
 mkdirSync(join(fixture,'components/src'),{recursive:true});
 const src=join(fixture,'components/src/index.js');
 writeFileSync(src,'import React from "react"; export const sameReact=React; export const label="before";');
 const first=load(await buildComponents({root:fixture,outDir:join(fixture,'out')}));
 assert.equal(first.window.AuroraWebDesignSystem_96e210.sameReact,first.window.React);
 assert.equal(first.window.AuroraWebDesignSystem_96e210.label,'before');first.window.close();
 writeFileSync(src,'import React from "react"; export const sameReact=React; export const label="after";');
 const second=load(await buildComponents({root:fixture,outDir:join(fixture,'out')}));
 assert.equal(second.window.AuroraWebDesignSystem_96e210.label,'after');second.window.close();
 writeFileSync(src,'export const broken = ;');
 await assert.rejects(buildComponents({root:fixture,outDir:join(fixture,'out')}));
}finally{rmSync(fixture,{recursive:true,force:true});}
console.log('component-build: source changes, shared React, all legacy exports and build errors passed');
