import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { readTokenModel } from '../tools/tokens/model.mjs';
import { serializePublicTokens } from '../tools/tokens/public-json.mjs';
const source = JSON.parse(readFileSync(new URL('../tokens/source.json', import.meta.url)));
const model = readTokenModel(source);
assert.equal(model.density.cozy['--ds-control-h'], '36px');
assert.equal(model.density.compact['--ds-control-h'], '30px');
const original = JSON.parse(readFileSync(new URL('../.tmp/migration/original/tokens.json', import.meta.url)));
assert.deepEqual(JSON.parse(serializePublicTokens(source)), original);
const duplicate = structuredClone(source);
duplicate.color.tokens.push(structuredClone(duplicate.color.tokens[0]));
assert.throws(() => readTokenModel(duplicate), /source.json.*ds-n-0.*duplicate/i);
const missing = structuredClone(source);
missing.color.tokens[0].value = '{ds-does-not-exist}';
assert.throws(() => readTokenModel(missing), /source.json.*ds-does-not-exist/);
const cyclic = structuredClone(source);
cyclic.color.tokens[0].value = '{ds-n-25}';
cyclic.color.tokens[1].value = '{ds-n-0}';
assert.throws(() => readTokenModel(cyclic), /source.json.*cycle/i);
console.log('token-model: public JSON, density, duplicates, missing references and cycles passed');
